### PR TITLE
fix Validator.js json-schema/lib/validate import

### PR DESCRIPTION
**Pull request by rbuels**

### CODE REVIEW

**Comment by neonstalwart** [comment]
hi @rbuels,

from what i see of the json-schema package, the [validate module](https://github.com/kriszyp/json-schema/tree/v0.2.1/lib/validate.js) is in the `lib` directory.  are we looking at the same thing?

**Comment by rbuels** [comment]
That commit is against aa68d, which doesn't seem to have a `lib` dir, see https://github.com/kriszyp/dbind/tree/aa68debbdbf3c7b301268e6858d8fe4ba6e58d50

**Comment by rbuels** [comment]
oh wait, json-schema, not dbind. right, nm.

**Comment by rbuels** [comment]
@neonstalwart ah, actually I remember what this is really about.  without that commit, the dojo build of my app fails with:

```
error(311) Missing dependency. module: dbind/Validator; dependency: json-schema/lib/validate
```

But maybe that's because of some mistake in the package.json in json-schema?  If I remove json-schema's package.json the build succeeds.

**Comment by neonstalwart** [comment]
yeah, i think this is because of the lib directory entry in json-schema's package.json :frowning:  

with AMD, it seems to be more common now to not use an implicit lib dir and opt for more explicit module ids.  

the dependency `'json-schema/lib/validate'`, used in dbind/Validator, follows that line of thinking so maybe you might want to open an issue for json-schema to adjust it's configuration.

in the meantime, i believe that you can override the package.json from your build like so:

``` js
packages: [
  'dojo',
  'dijit',
  'dojox',
  'dbind',
  {
    name: 'json-schema',
    // setting a location will bypass the directories.lib setting in the package.json
    location: '../json-schema'
  }
]
```

**Pull request closed without merging**
